### Libraries

In [2]:
import os
from sqlalchemy import create_engine
import pandas as pd
from IPython.display import display

#### Connection w/ DB and DF creation

In [3]:

# Creates de connection with Mysql DB
db_connection_str = 'mysql://root:555495@localhost/nothemetweets'
db_connection = create_engine(db_connection_str)

# Creates the dataframe accordingly to the given query
df_tabela_emocoes = pd.read_sql('SELECT * FROM tweets;', con=db_connection)

# Presentation of dataframe
display(df_tabela_emocoes.head(n=10))
print('Table has {:,} rows and {} columns'.format(df_tabela_emocoes.shape[0], df_tabela_emocoes.shape[1]))

                                             Content
0  "1031761728445530000","@Tixaa23 14 para eu ir ...
1  "1031761040462270000","@drexalvarez O meu like...
2  "1031760962372680000","Eu só queria conseguir ...
3  "1031760948250450000",":D que lindo dia !","Tu...
4  "1031760895985240000","@Primo_Resmungao Pq da ...
5  "1031760822543020000","@BadWolf_Wagner @DanieV...
6  "1031760780641710000","@Chyko661 @g1 [+] Carci...
7  "1031760749813800000","Aquela mina da limpeza,...
8  "1031760690778970000","@narryfools aqui, esper...
9  "1031760658600280000","@fefocaires se és feliz...

Table has 785,815 rows and 1 columns

### Manipulating and creating the dataframe with its desired columns

In [4]:
#string = df_tabela_emocoes.head(n=10).values
string_tabela_emocoes = df_tabela_emocoes.values
lista_string_raw = []
lista_string_constructed = [] 
dic_tweet = {}
for item_e in string_tabela_emocoes:
    lista_string_raw.append(item_e[0].split('","'))
for item_r in lista_string_raw:
    if len(item_r) == 3:
        if item_r[0][0] == '"' and item_r[2][-1] == '"':
            string_constructed = [item_r[0][1:]] + [item_r[1]] + [item_r[2][:-1]]
            lista_string_constructed.append(string_constructed)
    elif 1 < len(item_r) < 3:
        string_constructed = [item_r[0][1:]] + [item_r[1]] 
        lista_string_constructed.append(string_constructed)
for item_c in lista_string_constructed:
        if len(dic_tweet) == 0:
            dic_tweet['id'], dic_tweet['text'], dic_tweet['date'] = [], [], []
            dic_tweet['simbolo'], dic_tweet['sentimento'] = [], []
           
            dic_tweet['notOk'] = {}
            dic_tweet['notOk']['id'], dic_tweet['notOk']['text'], dic_tweet['notOk']['content'] = [], [], []
        elif len(item_c) == 3:     
            dic_tweet['id'] += [item_c[0]]
            dic_tweet['text'] += [item_c[1]]
            dic_tweet['date'] += [item_c[2]]
        elif len(item_c) == 2:
            dic_tweet['notOk']['id'] += [item_c[0]] 
            dic_tweet['notOk']['text'] += [item_c[1]]
        elif len(item_c) == 1:
            dic_tweet['notOk']['content'] += [item_c]

dict_tweet_constructed = {"id": dic_tweet['id'], "text": dic_tweet['text'], 
                            "date": dic_tweet['date']}
dict_tweet_constructed_nok = {"id": dic_tweet['notOk']['id'], 'text': dic_tweet['notOk']['text']}
tweet_df = pd.DataFrame(data=dict_tweet_constructed, columns=['id', 'text', 'date'])
tweet_df_not_ok = pd.DataFrame(data=dict_tweet_constructed_nok, columns=['id', 'text'])
print("\nDF with all data: ")
display(tweet_df)
print("DF with data loss: ")
display(tweet_df_not_ok)

DF with all data:

,id,text,date
0,1031761040462270000,@drexalvarez O meu like eu já dei na época :),Tue Aug 21 04:32:55 +0000 2018
1,1031760962372680000,Eu só queria conseguir comer alguma coisa pra ...,Tue Aug 21 04:32:37 +0000 2018
2,1031760948250450000,:D que lindo dia !,Tue Aug 21 04:32:33 +0000 2018
3,1031760895985240000,"@Primo_Resmungao Pq da pr jeito!!é uma oferta,...",Tue Aug 21 04:32:21 +0000 2018
4,1031760822543020000,"@BadWolf_Wagner @DanieVedo Eu entendi, mas iss...",Tue Aug 21 04:32:03 +0000 2018
...,...,...,...
699034,1050705141207360000,Acordar 8 horas é tão bom :),Fri Oct 12 11:10:01 +0000 2018
699035,1050706655049100000,"@mayckcunha Olá, Mayck. Você já é cliente Clar...",Fri Oct 12 11:16:02 +0000 2018
699036,1050705846907390000,Opa tava na merda mm e fiquei logo mais feliz ...,Fri Oct 12 11:12:49 +0000 2018
699037,1050705490232120000,@andrebraga2806 Foi como a tua lealdade :),Fri Oct 12 11:11:24 +0000 2018
699038,1050704920922520000,Feliz dia das crianças!! De hoje e de ontem......,Fri Oct 12 11:09:08 +0000 2018

DF with data loss:

                        id                                               text
0      1031756385741090000  @Haddad_Fernando @geraldoalckmin @MichelTemer ...
1      1031738562847360000  e intrigαs. Os melhores meses dα minhα vidα. p...
2      1031738560716720000  Hoje é um diα mαis que especiαl.. porque hoje,...
3      1031739485933980000  Se você encontrasse um gênio da lâmpada, quais...
4      1031728247975880000  @pmkiay Oii, eu vou realizar uma sessão de exi...
...                    ...                                                ...
86769  1050726048353080000     @PedroDerbli Vou sim :) Sábado estarei por lá
86770  1050713349141460000  @DAlckmim Olá, Diego! Você pode dar uma olhadi...
86771  1050723722066370000  Hoje partilho convosco o makeoff do layout de ...
86772  1050717857946980000  @FallinNautilus VC mora perto de mim Nada impe...
86773  1050711703858670000  Estes foram os guerreiros de 2017...Este ano, ...

[86774 rows x 2 columns]

### Inserting emotion analysis in the DF

In [5]:
positive_symbols = [ ":)", ": )", ":D", "xD", ":-)"]
negative_symbols = [ ":/", ":(", ":-(", ":´)", ":´´)", ":´("]
neutral_symbols = [ ':V', ':P', ':/']

symbols = [ ":)", ": )", ":D", "xD", ":-)", ':V', ':P', ':/', 
                        ":/", ":(", ":-(", ":´)", ":´´)", ":´("]

def symbol_matcher(text):
        splited_text = text.split()
        symbol_backwards = splited_text[-1::-1]
        for item in symbol_backwards:
            if item in symbols:
                return item
def felling_matcher(item):
        if item in positive_symbols:
                return "Positive"
        elif item in neutral_symbols:
                return "Neutral"
        elif item in negative_symbols:
                return "Negative"
                
tweet_df['symbol'] = tweet_df['text'].apply(symbol_matcher)
tweet_df['felling'] = tweet_df['symbol'].apply(felling_matcher)

print("\nDF with positive fellings: ".upper())
display(tweet_df.query('felling == "Positive"'))
print("DF with neutral fellings: ".upper())
display(tweet_df.query('felling == "Neutral"'))
print("DF with negative emotions: ".upper())
display(tweet_df.query('felling == "Negative"'))

DF WITH POSITIVE FELLINGS:

,id,text,date,symbol,felling
0,1031761040462270000,@drexalvarez O meu like eu já dei na época :),Tue Aug 21 04:32:55 +0000 2018,:),Positive
1,1031760962372680000,Eu só queria conseguir comer alguma coisa pra ...,Tue Aug 21 04:32:37 +0000 2018,:),Positive
2,1031760948250450000,:D que lindo dia !,Tue Aug 21 04:32:33 +0000 2018,:D,Positive
5,1031760780641710000,@Chyko661 @g1 [+] Carcinoma Hepatico (Cancer d...,Tue Aug 21 04:31:53 +0000 2018,:),Positive
6,1031760749813800000,"Aquela mina da limpeza, que tinha um marido co...",Tue Aug 21 04:31:46 +0000 2018,:),Positive
...,...,...,...,...,...
699034,1050705141207360000,Acordar 8 horas é tão bom :),Fri Oct 12 11:10:01 +0000 2018,:),Positive
699035,1050706655049100000,"@mayckcunha Olá, Mayck. Você já é cliente Clar...",Fri Oct 12 11:16:02 +0000 2018,:),Positive
699036,1050705846907390000,Opa tava na merda mm e fiquei logo mais feliz ...,Fri Oct 12 11:12:49 +0000 2018,:),Positive
699037,1050705490232120000,@andrebraga2806 Foi como a tua lealdade :),Fri Oct 12 11:11:24 +0000 2018,:),Positive
699038,1050704920922520000,Feliz dia das crianças!! De hoje e de ontem......,Fri Oct 12 11:09:08 +0000 2018,:),Positive

DF WITH NEUTRAL FELLINGS:

,id,text,date,symbol,felling
3,1031760895985240000,"@Primo_Resmungao Pq da pr jeito!!é uma oferta,...",Tue Aug 21 04:32:21 +0000 2018,:P,Neutral
4,1031760822543020000,"@BadWolf_Wagner @DanieVedo Eu entendi, mas iss...",Tue Aug 21 04:32:03 +0000 2018,:P,Neutral
12,1031760488705570000,Quando você joga com um youtuber que você segu...,Tue Aug 21 04:30:44 +0000 2018,:P,Neutral
46,1031761644349790000,@Primo_Resmungao @God_is_a_she A tua mulher pa...,Tue Aug 21 04:35:19 +0000 2018,:P,Neutral
60,1031758345361870000,@padilhafbpa Consegue baixar Discord no seu ce...,Tue Aug 21 04:22:13 +0000 2018,:P,Neutral
...,...,...,...,...,...
698893,1050719223826270000,"No momento morrendo de sono, mas já já a gente...",Fri Oct 12 12:05:59 +0000 2018,:P,Neutral
698897,1050717959503650000,"Para nós, o programa de sexta-feira é claro. C...",Fri Oct 12 12:00:57 +0000 2018,:P,Neutral
698942,1050717453964250000,@andrebento @RebeloNuno @iAModp @jotadaega Ehe...,Fri Oct 12 11:58:57 +0000 2018,:P,Neutral
699000,1050705395231150000,@PaulaCrystalina @pH1sugarfree @pact_pt É mais...,Fri Oct 12 11:11:02 +0000 2018,:P,Neutral
699025,1050705270169620000,@einjim :O :V,,:V,Neutral

DF WITH NEGATIVE EMOTIONS:

,id,text,date,symbol,felling
162,1031745690546970000,Pra sempre bonde do bodão em nossos corações! ...,Tue Aug 21 03:31:56 +0000 2018,:´),Negative
194,1031748903035690000,façam chamada cmg :) :(,Tue Aug 21 03:44:42 +0000 2018,:(,Negative
245,1031746569073250000,"@oioijuliana aaaa é só chamar, real hahah :) m...",Tue Aug 21 03:35:25 +0000 2018,:(,Negative
918,1031729986829470000,"Bebê, vc prefere sunshine ou bela mia?? Boa no...",Tue Aug 21 02:29:32 +0000 2018,:(,Negative
938,1031734111268940000,achei um filme legal :) to com sono :(,Tue Aug 21 02:45:55 +0000 2018,:(,Negative
...,...,...,...,...,...
697125,1049138183462690000,Do nada cara :(,Mon Oct 08 03:23:29 +0000 2018,:(,Negative
697353,1050762088614910000,"@nwtsz é bom mesmo Nats, mas o meu ja ta no fi...",Fri Oct 12 14:56:18 +0000 2018,:´),Negative
697864,1050743043672950000,vou ter churrasco :) é com gente da igreja que...,Fri Oct 12 13:40:38 +0000 2018,:(,Negative
698167,1050727231348250000,Vejo aqueles memes: quando vc recebe visita :(...,Fri Oct 12 12:37:48 +0000 2018,:(,Negative
698249,1050727645317650000,"@gustavodocil @Allanmnez Não, tudo bem hahaha ...",Fri Oct 12 12:39:26 +0000 2018,:(,Negative

In [6]:
cwd = os.getcwd()
path = cwd + "/tweets.csv"
tweet_df.to_csv(path, index=False)

#tweet_df.to_csv(r"C:\Users\pablo\DevStuff\DevProjects\projeto_dados\tweet_emotions.csv", index=False)